// Phase 10: Email Orchestrator
import { emailService } from './emailService'
import { markdownGenerator } from '@/lib/scope/markdownGenerator'
import type { 
  ScopeDocument, 
  ClientSummary 
} from '@/types/scope'
import type { 
  EmailDelivery,
  EmailAttachment,
  ScopeMdEmail,
  ClientSummaryEmail
} from '@/types/email'

export class EmailOrchestrator {
  /**
   * Send all emails after SCOPE.md generation
   */
  async sendCompletionEmails(
    scope: ScopeDocument,
    clientSummary: ClientSummary,
    conversationId: string
  ): Promise<{
    davidEmail: EmailDelivery
    clientEmail: EmailDelivery
  }> {
    try {
      // Generate attachments
      const scopeMdAttachment = this.generateScopeMdAttachment(scope)
      const clientPdfAttachment = await this.generateClientPdfAttachment(clientSummary)
      
      // Send emails in parallel
      const [davidEmail, clientEmail] = await Promise.all([
        this.sendScopeMdToDavid(scope, conversationId, scopeMdAttachment),
        this.sendClientSummary(scope, clientSummary, clientPdfAttachment)
      ])
      
      return {
        davidEmail,
        clientEmail
      }
      
    } catch (error) {
      console.error('Email orchestration failed:', error)
      throw error
    }
  }
  
  /**
   * Send SCOPE.md to David
   */
  async sendScopeMdToDavid(
    scope: ScopeDocument,
    conversationId: string,
    attachment: EmailAttachment
  ): Promise<EmailDelivery> {
    const emailData: ScopeMdEmail = {
      to: process.env.DAVID_EMAIL || 'david@applicreations.com',
      from: process.env.INTROSPECT_FROM_EMAIL || 'Introspect <introspect@applicreations.com>',
      subject: '', // Will be generated by template
      projectName: scope.section1_executiveSummary.projectName,
      clientName: scope.section3_clientInformation.fullName,
      clientEmail: scope.section3_clientInformation.email,
      websiteType: scope.section1_executiveSummary.websiteType,
      packageTier: scope.section2_projectClassification.recommendedPackage,
      totalInvestment: scope.section13_investmentSummary.totalProjectInvestment,
      conversationId,
      attachments: [attachment]
    }
    
    return await emailService.sendScopeMdToDavid(emailData)
  }
  
  /**
   * Send client summary to user
   */
  async sendClientSummary(
    scope: ScopeDocument,
    clientSummary: ClientSummary,
    attachment: EmailAttachment
  ): Promise<EmailDelivery> {
    const emailData: ClientSummaryEmail = {
      to: scope.section3_clientInformation.email,
      from: process.env.INTROSPECT_FROM_EMAIL || 'Introspect <introspect@applicreations.com>',
      subject: '', // Will be generated by template
      clientName: scope.section3_clientInformation.fullName,
      projectName: scope.section1_executiveSummary.projectName,
      nextSteps: clientSummary.nextSteps,
      davidEmail: process.env.DAVID_EMAIL || 'david@applicreations.com',
      davidPhone: process.env.DAVID_PHONE || '(555) 123-4567',
      davidContactInfo: {
        email: process.env.DAVID_EMAIL || 'david@applicreations.com',
        phone: process.env.DAVID_PHONE || '(555) 123-4567',
        calendlyUrl: process.env.DAVID_CALENDLY_URL || 'https://calendly.com/applicreations'
      },
      attachments: [attachment]
    }
    
    return await emailService.sendClientSummary(emailData)
  }
  
  /**
   * Generate SCOPE.md attachment
   */
  generateScopeMdAttachment(scope: ScopeDocument): EmailAttachment {
    const markdown = markdownGenerator.generateMarkdown(scope)
    const filename = `SCOPE_${scope.section1_executiveSummary.projectName.replace(/\s+/g, '_')}.md`
    
    return {
      filename,
      content: markdown,
      contentType: 'text/markdown',
      encoding: 'utf-8'
    }
  }
  
  /**
   * Generate client PDF attachment
   */
  async generateClientPdfAttachment(
    clientSummary: ClientSummary
  ): Promise<EmailAttachment> {
    // Call PDF generation endpoint
    const response = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000'}/api/scope/generate-pdf`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        html: this.generateClientPdfHtml(clientSummary)
      })
    })
    
    if (!response.ok) {
      throw new Error('PDF generation failed')
    }
    
    const pdfBuffer = await response.arrayBuffer()
    const filename = `${clientSummary.projectName.replace(/\s+/g, '_')}_Summary.pdf`
    
    // Convert to base64 for email attachment
    const base64 = Buffer.from(pdfBuffer).toString('base64')
    
    return {
      filename,
      content: base64,
      contentType: 'application/pdf',
      encoding: 'base64'
    }
  }
  
  /**
   * Generate HTML for client PDF
   */
  private generateClientPdfHtml(clientSummary: ClientSummary): string {
    // Use the client summary generator from Phase 9
    const { clientSummaryGenerator } = require('@/lib/scope/clientSummaryGenerator')
    return clientSummaryGenerator.generateHTML(clientSummary)
  }
}

export const emailOrchestrator = new EmailOrchestrator()

